version: '3'
services:
  vue-app:
    build:
      context: frontend-app
      dockerfile: Dockerfile
    working_dir: /app
    container_name: vue-app
    ports:
      - "8080:8080"
    volumes:
      - ./frontend-app:/app
    environment:
      - NODE_ENV=development
    networks:
      - optimum7

  #PHP Service
  app:
    build:
      context: backend-app
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./backend-app/:/var/www
      - ./backend-app/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - optimum7

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend-app:/var/www
      - ./backend-app/docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - optimum7

  #MySQL Service
  db:
    image: 'bitnami/mysql:latest'
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: optimum7
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./backend-app/docker/database/my.cnf:/etc/mysql/my.cnf
    networks:
      - optimum7

networks:
  optimum7:
    driver: bridge

volumes:
  mysql-data:
    driver: local