version: '3'
services:
  optimum7-vue-app:
    build:
      context: frontend-app
      dockerfile: Dockerfile
    working_dir: /app
    container_name: optimum7-vue-app
    ports:
      - "8080:8080"
    volumes:
      - ./frontend-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - optimum7

  #PHP Service
  optimum7-app:
    build:
      context: backend-app
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: optimum7-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./backend-app/:/var/www
      - ./backend-app/docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - /var/www/vendor
    networks:
      - optimum7
    command: /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf


  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend-app:/var/www
      - ./backend-app/docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - optimum7

  #MySQL Service
  optimum7-db:
    image: 'bitnami/mysql:latest'
    container_name: optimum7-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: optimum7
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data-optimum7:/bitnami/mysql/data
      - ./backend-app/docker/database/my.cnf:/etc/mysql/my.cnf
      - './backend-app/docker/database/init-testing-db.sh:/docker-entrypoint-initdb.d/init-testing-db.sh'
    networks:
      - optimum7

networks:
  optimum7:
    driver: bridge

volumes:
  mysql-data-optimum7:
    driver: local